In [1]:
#import
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from functions import PmCc,linear_regression

In [2]:
# Function to convert a pandas dataframe to a dictionary for easier data manipulation
def dataframe_to_dictionary(df):
    dictionary = {}
    for header in df:
        dictionary[header] = [data for data in df[header]]
    return dictionary

In [3]:
##All data Imports
##ViolentCrimesSheet = pd.read_excel("statistic_id288256_number-of-violent-crime-offences-in-england-and-wales-2007-2022.xlsx", "Data", header=5)

#convert to more managable data
##dataViolentCrimesSheet = dataframe_to_dictionary(ViolentCrimesSheet)
#print(dataViolentCrimesSheet)
##https://www.statista.com/statistics/288256/violent-crimes-in-england-and-wales/

##VideoGameSheet = pd.read_excel("statistic_id300521_uk-gaming-reach-2007-2021.xlsx", "Data", header=4)
##dataVideoGameSheet = dataframe_to_dictionary(VideoGameSheet)
##https://www.statista.com/statistics/300521/gaming-in-the-united-kingdom/

##AgeOfGamersSheet = pd.read_excel("statistic_id300513_uk-gaming-reach-2013-2021-by-age-group-and-gender (1) (1) (2).xlsx", "Data", header=4)
##dataAgeOfGamersSheet = dataframe_to_dictionary(AgeOfGamersSheet)
##https://www.statista.com/statistics/300513/gaming-by-demographic-group-uk/

##GenderOfGamersSheet = pd.read_excel("statistic_id300513_uk-gaming-reach-2013-2021-by-age-group-and-gender (1) (1) (2).xlsx", "Data2", header=4)
##dataGenderOfGamersSheet = dataframe_to_dictionary(GenderOfGamersSheet)
##https://www.statista.com/statistics/300513/gaming-by-demographic-group-uk/

##AgeOfGamersSheetsmall = pd.read_excel("statistic_id300513_uk-gaming-reach-2013-2021-by-age-group-and-gender (1) (1) (2).xlsx", "Data3", header=4)
##dataAgeOfGamersSheetsmall = dataframe_to_dictionary(AgeOfGamersSheetsmall)
##https://www.statista.com/statistics/300513/gaming-by-demographic-group-uk/

##SuicideRateAge = pd.read_excel("statistic_id289102_suicide-rate-in-england-and-wales-2021-by-age (1).xlsx", "Data", header=4)
##dataSuicideRateAge = dataframe_to_dictionary(SuicideRateAge)
##https://www.statista.com/statistics/289102/suicide-rate-in-the-united-kingdom-uk-by-age/

##SuicideRate = pd.read_excel("statistic_id282160_suicide-rate-in-england-and-wales-2000-2021 (1).xlsx", "Data", header=4)
##dataSuicideRate = dataframe_to_dictionary(SuicideRate)
##https://www.statista.com/statistics/282160/suicide-rate-in-the-united-kingdom-uk-since-2000/

##HomicidePercentage = pd.read_excel("Figure_10__Suspects_convicted_of_homicide_show_a_younger_age_profile (2).xlsx", "Data", header=4)
##dataHomicidePercentage = dataframe_to_dictionary(HomicidePercentage) 
##https://www.ons.gov.uk/peoplepopulationandcommunity/crimeandjustice/articles/homicideinenglandandwales/yearendingmarch2021

##HomicidePercentages = pd.read_excel("Figure_10__Suspects_convicted_of_homicide_show_a_younger_age_profile (2).xlsx", "Data2", header=4)
##dataHomicidePercentages = dataframe_to_dictionary(HomicidePercentages) 
##https://www.ons.gov.uk/peoplepopulationandcommunity/crimeandjustice/articles/homicideinenglandandwales/yearendingmarch2021

##DrugDeaths = pd.read_excel("Figure_10__Suspects_convicted_of_homicide_show_a_younger_age_profile (2).xlsx", "Data3", header=4)
##dataDrugDeaths = dataframe_to_dictionary(DrugDeaths) 
##https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/deaths/bulletins/deathsrelatedtodrugpoisoninginenglandandwales/2021registrations

##SexualOffencess = pd.read_excel("Figure_10__Suspects_convicted_of_homicide_show_a_younger_age_profile (2).xlsx", "Data4", header=4)
##dataSexualOffencess = dataframe_to_dictionary(SexualOffencess) 
##https://www.statista.com/statistics/315500/sexual-offences-england-wales/

##PopGames = pd.read_excel("statistic_id274072_best-selling-video-games-in-the-uk-2021.xlsx", "Data", header=4)
##dataPopGames = dataframe_to_dictionary(PopGames) 
##https://www.statista.com/statistics/274072/most-popular-games-in-the-united-kingdom-uk-by-unit-sales/

##MorePopGames = pd.read_excel("statistic_id274072_best-selling-video-games-in-the-uk-2021.xlsx", "Data.3", header=4)
##dataMorePopGames = dataframe_to_dictionary(MorePopGames)
##https://www.statista.com/statistics/274072/most-popular-games-in-the-united-kingdom-uk-by-unit-sales/

##ShooterGames = pd.read_excel("statistic_id274072_best-selling-video-games-in-the-uk-2021.xlsx", "Data2", header=4)
##dataShooterGames = dataframe_to_dictionary(ShooterGames)
##https://www.statista.com/statistics/1280526/gb-weekly-time-video-games-shooter-players/

##GenreOfGames = pd.read_excel("statistic_id274072_best-selling-video-games-in-the-uk-2021.xlsx", "Data3", header=4)
##dataGenreOfGames = dataframe_to_dictionary(GenreOfGames)
##https://gametree.me/blog/global-gamer-insights-report/#:~:text=For%20genre%20popularity%2C%20Action%20is%20rated%20as%20the,genres%20have%20a%20less%20than%2050%25%20preference%20rating.

##homicidesByYear = pd.read_excel("statistic_id283093_number-of-homicides-in-england-and-wales-2002-2022.xlsx", "Data", header=4)
##datahomicidesByYear = dataframe_to_dictionary(homicidesByYear)
##https://www.statista.com/statistics/283093/homicides-in-england-and-wales/

In [4]:
df = pd.read_excel("statistic_id274072_best-selling-video-games-in-the-uk-2021.xlsx", "Data", header = 2)
df.head()
print(df)

x = dataframe_to_dictionary(df)
best_selling_games1 = x["Best-selling video games in the UK 2021"]

best_selling_games = np.array(best_selling_games1)
print(best_selling_games)

x = dataframe_to_dictionary(df)
best_selling_sales1 = x["Sales"]

best_selling_sales = np.array(best_selling_sales1)
print(best_selling_sales)

   Best-selling video games in the UK 2021    Sales  Percentage Unnamed: 3  \
0                                  FIFA 22  2338778       21.75        NaN   
1                   Call Of Duty: Vanguard   975339        9.07          y   
2                        Gand Theft Auto V   967242        9.00          y   
3                                  FIFA 21   602224        5.60        NaN   
4                     Mario Kart 8 Deluxe*   599881        5.58        NaN   
5         Call of Duty: Black Ops Cold War   549490        5.11          y   
6                Spider-Man: Miles Morales   505803        4.70        NaN   
7           Animal Crossing: New Horizons*   457407        4.25        NaN   
8                                Minecraft   445124        4.14        NaN   
9                    Red Dead Redemption 2   395669        3.68          y   
10                                 F1 2021   371470        3.45        NaN   
11                               Far Cry 6   371020        3.45 

In [5]:
fig = px.bar(
    x=best_selling_sales,  # sales on the x-axis
    y=best_selling_games,  # games on the y-axis
    orientation='h',  # specify horizontal orientation
    labels={'x': 'Number of UK sales in 2021', 'y': 'Games (Top 20 UK sold in 2021)'},
    title='UK video game sales in 2021'
)

fig.show()

In [6]:
df = pd.read_excel("statistic_id274072_best-selling-video-games-in-the-uk-2021.xlsx", "Data.3", header = 2)
df.head()
print(df)

x = dataframe_to_dictionary(df)
cert_18_percentage1 = x["Cert 18 percentage"]

cert_18_percentage = np.array(cert_18_percentage1)
print(cert_18_percentage)

x = dataframe_to_dictionary(df)
not_cert_18_percentage1 = x["not Cert 18 without fifa 22 percentage"]

not_cert_18_percentage = np.array(not_cert_18_percentage1)
print(not_cert_18_percentage)

x = dataframe_to_dictionary(df)
Fifa_221 = x["Fifa 22 Percentage"]

Fifa_22 = np.array(Fifa_221)
print(Fifa_22)

x = dataframe_to_dictionary(df)
total_percentage_games1 = x["Total percentage"]

total_percentage_games = np.array(total_percentage_games1)
print(total_percentage_games)

   Cert 18  Cert 18 percentage  not Cert 18 with fifa 22  \
0  4185225               38.92                   6567719   

   not Cert 18 with fifa 22 percentage  Fifa 22  Fifa 22 Percentage  \
0                                61.08  2338778               21.75   

   not Cert 18 without fifa 22  not Cert 18 without fifa 22 percentage  \
0                      4228941                                   39.33   

      Total  Total percentage  
0  10752944               100  
[38.92]
[39.33]
[21.75]
[100]


In [7]:
#*venn diagram having toruble showing on VS but does on Cocalc



#Type_of_games = ['Certficate 18 (4185225)', 'Fifa 22 (2338778)', 'Not certificate 18 excluding fifa 22 (4228941)']
 
#data = [cert_18_percentage, Fifa_22, not_cert_18_percentage]
 
# Define different shades of blue
#colors = ['#1f77b4', '#4d94ff', '#99c2ff']

# Create a pie chart using Matplotlib and NumPy
#fig, ax = plt.subplots(figsize=(10, 7))
#ax.pie(data, labels=Type_of_games, autopct='%1.1f%%', startangle=90, colors=colors)

# Equal aspect ratio ensures that the pie is drawn as a circle
#ax.axis('equal')  

#plt.title("Pie chart to show top 20 UK games sold by certificate")
#plt.legend(loc='upper left')

# Show the plot
#plt.show() 

In [8]:
df = pd.read_excel("statistic_id274072_best-selling-video-games-in-the-uk-2021.xlsx", "Data2", header = 2)
df.head()
print(df)

x = dataframe_to_dictionary(df)
game_genre_use1= x["Use"]

game_genre_use = np.array(game_genre_use1)
print(game_genre_use)

x = dataframe_to_dictionary(df)
game_genre_shooter1 = x["Shooter gamers"]

game_genre_shooter = np.array(game_genre_shooter1)
print(game_genre_shooter)

x = dataframe_to_dictionary(df)
game_genre_all1 = x["All genre gamers"]

game_genre_all = np.array(game_genre_all1)
print(game_genre_all)

           Use  Shooter gamers  All genre gamers
0        Heavy              34                23
1       Medium              15                17
2        Light              29                29
3  Ultra light              14                21
4   Don't know               6                 7
['Heavy' 'Medium' 'Light' 'Ultra light' "Don't know"]
[34 15 29 14  6]
[23 17 29 21  7]


In [9]:
X = ['Heavy','Medium','Light','Ultra light', 'Do not know']

# Create traces
trace1 = go.Bar(
    x=X,
    y=game_genre_shooter,
    name='Shooter genre gamers',
    marker=dict(color='rgba(0, 0, 255, 0.7)'),  
)

trace2 = go.Bar(
    x=X,
    y=game_genre_all,
    name='All genre gamers',
    marker=dict(color='rgba(0, 0, 255, 0.5)'), 
)

data = [trace1, trace2]

# Create layout
layout = go.Layout(
    title='Comparison between all and shooter adult gaming genres in the UK',
    xaxis=dict(title='Genre extent of use'),
    yaxis=dict(title='Percentage of adult gamers'),
    barmode='group'
)

# Create figure
fig = go.Figure(data=data, layout=layout)

# Show the figure
fig.show()

In [10]:
df = pd.read_excel("statistic_id300513_uk-gaming-reach-2013-2021-by-age-group-and-gender (1) (1) (2).xlsx", "Data3", header = 2)
df.head()
print(df)

z = dataframe_to_dictionary(df)
smaller_year1 = z["Year"]

smaller_year = np.array(smaller_year1)
print(smaller_year)

z = dataframe_to_dictionary(df)
gamer_age_16 = z["16-24"]

gamer_age_161 = np.array(gamer_age_16)
print(gamer_age_161)

z = dataframe_to_dictionary(df)
gamer_age_25 = z["25-34"]

gamer_age_251 = np.array(gamer_age_25)
print(gamer_age_251)

z = dataframe_to_dictionary(df)
gamer_age_35 = z["35-44"]

gamer_age_351 = np.array(gamer_age_35)
print(gamer_age_351)

z = dataframe_to_dictionary(df)
gamer_age_45 = z["45-54"]

gamer_age_451 = np.array(gamer_age_45)
print(gamer_age_451)

z = dataframe_to_dictionary(df)
gamer_age_55 = z["55-64"]

gamer_age_551 = np.array(gamer_age_55)
print(gamer_age_551)

z = dataframe_to_dictionary(df)
gamer_age_65 = z["65-74"]

gamer_age_651 = np.array(gamer_age_65)
print(gamer_age_651)


   Year  16-24  25-34  35-44  45-54  55-64  65-74
0  2017     70     49     40     29     23     16
1  2018     65     59     36     35     23     23
2  2019     73     52     41     40     34     25
3  2020     92     82     76     62     43     22
4  2021     88     79     73     62     47     26
[2017 2018 2019 2020 2021]
[70 65 73 92 88]
[49 59 52 82 79]
[40 36 41 76 73]
[29 35 40 62 62]
[23 23 34 43 47]
[16 23 25 22 26]


In [11]:
np.random.seed(42)

x = smaller_year

plot = go.Figure(data=[
    go.Bar(
        name='16-24',
        x=x,
        y=gamer_age_161,
        marker_color='rgba(30, 144, 255, 0.7)' 
    ),
    go.Bar(
        name='25-34',
        x=x,
        y=gamer_age_251,
        marker_color='rgba(0, 0, 255, 0.7)'
    ),
    go.Bar(
        name='35-44',
        x=x,
        y=gamer_age_351,
        marker_color='rgba(0, 0, 255, 0.8)'
    ),
    go.Bar(
        name='45-54',
        x=x,
        y=gamer_age_451,
        marker_color='rgba(0, 0, 255, 0.9)'
    ),
    go.Bar(
        name='55-64',
        x=x,
        y=gamer_age_551,
        marker_color='rgba(0, 0, 255, 1.0)'
    ),
    go.Bar(
        name='65-74',
        x=x,
        y=gamer_age_651,
        marker_color='rgba(70, 130, 180, 1.0)'
    )
])

plot.update_layout(
    xaxis_title="Years",
    yaxis_title="Percentage of gamers",
    title="Percentage of gamers by age group from 2017-2021",
    legend=dict(x=1, y=1),
)

plot.show()

In [12]:
df = pd.read_excel("statistic_id300513_uk-gaming-reach-2013-2021-by-age-group-and-gender (1) (1) (2).xlsx", "Data2", header = 2)
df.head()
print(df)

z = dataframe_to_dictionary(df)
smaller_year1 = z["Year"]

smaller_year = np.array(smaller_year1)
print(smaller_year)

z = dataframe_to_dictionary(df)
Male_gamer1 = z["Male"]

Male_gamer = np.array(Male_gamer1)
print(Male_gamer)

z = dataframe_to_dictionary(df)
Female_gamer1 = z["Female"]

Female_gamer = np.array(Female_gamer1)
print(Female_gamer)

   Year  Male  Female
0  2017    41      31
1  2018    44      32
2  2019    46      32
3  2020    61      63
4  2021    63      56
[2017 2018 2019 2020 2021]
[41 44 46 61 63]
[31 32 32 63 56]


In [13]:
X = ['2017', '2018', '2019', '2020', '2021']

X_axis = np.arange(len(X))
  
fig = go.Figure()

fig.add_trace(go.Bar(
    x=X_axis - 0.2,
    y=Male_gamer,
    width=0.4,
    name='Male gamer',
    marker_color='rgba(0, 0, 255, 0.7)'  # Adjust the RGB values and alpha as needed
))

fig.add_trace(go.Bar(
    x=X_axis + 0.2,
    y=Female_gamer,
    width=0.4,
    name='Female gamer',
    marker_color='rgba(0, 0, 255, 0.5)'
))

fig.update_layout(
    xaxis=dict(tickvals=X_axis, ticktext=X),
    xaxis_title="Years",
    yaxis_title="Percentage of gender are gamers",
    title="Adult gaming yearly by gender in the UK from 2017-2021",
    legend=dict(x=1, y=1),
)

fig.show()

In [14]:
df = pd.read_excel("Figure_10__Suspects_convicted_of_homicide_show_a_younger_age_profile (2).xlsx", "Data", header = 2)
df.head()
print(df)

z = dataframe_to_dictionary(df)
smaller_year1 = z["Year"]

smaller_year = np.array(smaller_year1)
print(smaller_year)

z = dataframe_to_dictionary(df)
homicide_age_16 = z["16-24"]

homicide_age_161 = np.array(homicide_age_16)
print(homicide_age_161)

z = dataframe_to_dictionary(df)
homicide_age_25 = z["25-34"]

homicide_age_251 = np.array(homicide_age_25)
print(homicide_age_251)

z = dataframe_to_dictionary(df)
homicide_age_35 = z["35-44"]

homicide_age_351 = np.array(homicide_age_35)
print(homicide_age_351)

z = dataframe_to_dictionary(df)
homicide_age_45 = z["45-54"]

homicide_age_451 = np.array(homicide_age_45)
print(homicide_age_451)

z = dataframe_to_dictionary(df)
homicide_age_55 = z["55-64"]

homicide_age_551 = np.array(homicide_age_55)
print(homicide_age_551)

z = dataframe_to_dictionary(df)
homicide_age_65 = z["65-74"]

homicide_age_651 = np.array(homicide_age_65)
print(homicide_age_651)

   Year  16-24  25-34  35-44  45-54  55-64  65-74
0  2017   28.5   25.5     23   13.5    6.5    1.0
1  2018   25.5   22.5     26   18.0    3.0    3.5
2  2019   26.0   24.0     23   13.0    3.5    6.0
3  2020   29.5   26.5     20   12.5    3.5    4.0
4  2021   27.0   31.0     20   12.0    4.0    3.5
[2017 2018 2019 2020 2021]
[28.5 25.5 26.  29.5 27. ]
[25.5 22.5 24.  26.5 31. ]
[23 26 23 20 20]
[13.5 18.  13.  12.5 12. ]
[6.5 3.  3.5 3.5 4. ]
[1.  3.5 6.  4.  3.5]


In [15]:
plot = go.Figure(data=[
    go.Bar(
        name='16-24',
        x=x,
        y=homicide_age_161,
        marker_color='rgba(255, 0, 0, 0.7)' 
    ),
    go.Bar(
        name='25-34',
        x=x,
        y=homicide_age_251,
        marker_color='rgba(255, 69, 0, 0.7)'
    ),
    go.Bar(
        name='35-44',
        x=x,
        y=homicide_age_351,
        marker_color='rgba(255, 99, 71, 0.8)'
    ),
    go.Bar(
        name='45-54',
        x=x,
        y=homicide_age_451,
        marker_color='rgba(255, 0, 0, 0.9)'
    ),
    go.Bar(
        name='55-64',
        x=x,
        y=homicide_age_551,
        marker_color='rgba(220, 20, 60, 1.0)'
    ),
    go.Bar(
        name='65-74',
        x=x,
        y=homicide_age_651,
        marker_color='rgba(255, 69, 0, 1.0)'
    )
])

plot.update_layout(
    xaxis_title="Years",
    yaxis_title="Homicide Rate",
    title="Homicide Rate by Age Group from 2017-2021",
    legend=dict(x=1, y=1),
)

plot.show()

In [16]:
df = pd.read_excel("statistic_id300513_uk-gaming-reach-2013-2021-by-age-group-and-gender (1) (1) (2).xlsx", "Data2", header = 2)
df.head()
print(df)

z = dataframe_to_dictionary(df)
smaller_year = z["Year"]
print(smaller_year)

z = dataframe_to_dictionary(df)
male_gamer = z["Male"]
print(male_gamer)

z = dataframe_to_dictionary(df)
female_gamer = z["Female"]
print(female_gamer)

   Year  Male  Female
0  2017    41      31
1  2018    44      32
2  2019    46      32
3  2020    61      63
4  2021    63      56
[2017, 2018, 2019, 2020, 2021]
[41, 44, 46, 61, 63]
[31, 32, 32, 63, 56]


In [17]:
X = ['2017', '2018', '2019', '2020', '2021']

X_axis = np.arange(len(X))
  
fig = go.Figure()

fig.add_trace(go.Bar(
    x=X_axis - 0.2,
    y=male_gamer,
    width=0.4,
    name='Male gamer',
    marker=dict(color='rgba(30, 144, 255, 0.7)')  # Adjust the RGB values and alpha as needed
))

fig.add_trace(go.Bar(
    x=X_axis + 0.2,
    y=female_gamer,
    width=0.4,
    name='Female gamer',
    marker=dict(color='rgba(0, 0, 255, 0.7)')
))

fig.update_layout(
    xaxis=dict(tickvals=X_axis, ticktext=X),
    xaxis_title="Years",
    yaxis_title="Percentage of gamers in the UK",
    title="UK video gamers by adult gender from 2017-2021",
    legend=dict(x=0.75, y=1),
)

fig.show()

In [18]:
df = pd.read_excel("Figure_10__Suspects_convicted_of_homicide_show_a_younger_age_profile (2).xlsx", "Data2", header = 2)
df.head()
print(df)

z = dataframe_to_dictionary(df)
smaller_year = z["Year"]
print(smaller_year)

z = dataframe_to_dictionary(df)
male_homicide = z["Male"]
print(male_homicide)

z = dataframe_to_dictionary(df)
female_homicide = z["Female"]
print(female_homicide)

   Year  Male  Female
0  2017    76      24
1  2018    96       4
2  2019    92       8
3  2020    93       7
4  2021    94       6
[2017, 2018, 2019, 2020, 2021]
[76, 96, 92, 93, 94]
[24, 4, 8, 7, 6]


In [19]:
X = ['2017', '2018', '2019', '2020', '2021']

X_axis = np.arange(len(X))
  
fig = go.Figure()

fig.add_trace(go.Bar(
    x=X_axis - 0.2,
    y=male_homicide,
    width=0.4,
    name='Male homicider',
    marker_color='rgba(255, 0, 0, 0.7)'  # Adjust the RGB values and alpha as needed
))

fig.add_trace(go.Bar(
    x=X_axis + 0.2,
    y=female_homicide,
    width=0.4,
    name='Female homicider',
    marker_color='rgba(255, 69, 0, 0.7)'
))

fig.update_layout(
    xaxis=dict(tickvals=X_axis, ticktext=X),
    xaxis_title="Years",
    yaxis_title="Percentage of homicide offences",
    title="Adult homicide offences yearly by gender in the UK from 2017-2021",
    legend=dict(x=1, y=1),
)

fig.show()

In [20]:
df = pd.read_excel("statistic_id289102_suicide-rate-in-england-and-wales-2021-by-age (1).xlsx", "Data", header = 2)
df.head()
print(df)

z = dataframe_to_dictionary(df)
age_group = z["Age"]
print(age_group)

z = dataframe_to_dictionary(df)
suicide_rate_age = z["Suicide rate"]
print(suicide_rate_age)

     Age  Suicide rate
0  16-24          8.55
1  25-34         11.90
2  35-44         13.45
3  45-54         14.70
4  55-64         11.75
5  65-74          7.90
['16-24', '25-34', '35-44', '45-54', '55-64', '65-74']
[8.55, 11.9, 13.45, 14.7, 11.75, 7.9]


In [21]:
fig = go.Figure()

fig.add_trace(go.Bar(
    x=age_group,
    y=suicide_rate_age,
    marker_color='rgba(255, 0, 0, 0.7)'  # Adjust the RGB values and alpha as needed
))

fig.update_layout(
    xaxis_title="Age group",
    yaxis_title="Adult suicide rate",
    title="UK adult suicide rate in 2021 by age group",
    xaxis=dict(tickangle=45),
)

fig.show()

In [22]:
df = pd.read_excel("statistic_id288256_number-of-violent-crime-offences-in-england-and-wales-2007-2022.xlsx", "Data", header = 3)
df.head()
print(df)

x = dataframe_to_dictionary(df)
violent_crimes1 = x["Crimes"]

z = dataframe_to_dictionary(df)
data_dates1 = z["Date"]

violent_crimes = np.array(violent_crimes1)
print(violent_crimes)

data_dates = np.array(data_dates1)
print(data_dates)

    Date   Crimes
0   2007   814865
1   2008   748779
2   2009   709008
3   2010   699011
4   2011   665486
5   2012   626720
6   2013   601141
7   2014   634625
8   2015   778198
9   2016   992343
10  2017  1161592
11  2018  1398961
12  2019  1674995
13  2020  1768182
14  2021  1775159
15  2022  2103151
[ 814865  748779  709008  699011  665486  626720  601141  634625  778198
  992343 1161592 1398961 1674995 1768182 1775159 2103151]
[2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020
 2021 2022]


In [23]:
df = pd.read_excel("Figure_10__Suspects_convicted_of_homicide_show_a_younger_age_profile (2).xlsx", "Data5", header = 2)
df.head()
print(df)

y = dataframe_to_dictionary(df)
data_dates = y["Year"]

y = dataframe_to_dictionary(df)
sexual_offences1 = y["Sexual Offences"]

data_dates = np.array(data_dates1)
print(data_dates)

sexual_offences = np.array(sexual_offences1)
print(sexual_offences)

    Year  Sexual Offences
0   2007            56042
1   2008            52166
2   2009            50185
3   2010            53006
4   2011            53940
5   2012            52760
6   2013            53599
7   2014            64232
8   2015            88576
9   2016           107209
10  2017           122944
11  2018           152684
12  2019           164261
13  2020           163171
14  2021           147890
15  2022           194683
[2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020
 2021 2022]
[ 56042  52166  50185  53006  53940  52760  53599  64232  88576 107209
 122944 152684 164261 163171 147890 194683]


In [24]:
df = pd.read_excel("statistic_id828895_number-of-possession-of-weapon.xlsx", "Data", header = 2)
df.head()
print(df)

y = dataframe_to_dictionary(df)
weapon_possession1 = y["weapon possession"]

z = dataframe_to_dictionary(df)
data_dates = z["Year"]

data_dates = np.array(data_dates1)
print(data_dates)

weapon_possession = np.array(weapon_possession1)
print(weapon_possession)

    Year  weapon possession
0   2007              38937
1   2008              37079
2   2009              35662
3   2010              28758
4   2011              26327
5   2012              23688
6   2013              19910
7   2014              20623
8   2015              21890
9   2016              25830
10  2017              31307
11  2018              39052
12  2019              46469
13  2020              47648
14  2021              44669
15  2022              49094
[2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020
 2021 2022]
[38937 37079 35662 28758 26327 23688 19910 20623 21890 25830 31307 39052
 46469 47648 44669 49094]


In [25]:
df = pd.read_excel("statistic_id282160_suicide-rate-in-england-and-wales-2000-2021 (1).xlsx", "Data", header = 3)
df.head()
print(df)

x = dataframe_to_dictionary(df)
data_dates1 = x["Date"]

y = dataframe_to_dictionary(df)
suicide_rate1 = y["Suicide rate "]

data_dates = np.array(data_dates1)
print(data_dates)

suicide_rate = np.array(suicide_rate1)
print(suicide_rate)

    Date  Suicide rate 
0   2007            9.5
1   2008            9.0
2   2009            9.5
3   2010            9.6
4   2011            9.3
5   2012            9.9
6   2013            9.8
7   2014           10.4
8   2015           10.3
9   2016           10.3
10  2017            9.7
11  2018            9.4
12  2019           10.5
13  2020           11.0
14  2021           10.0
15  2022           10.7
[2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020
 2021 2022]
[ 9.5  9.   9.5  9.6  9.3  9.9  9.8 10.4 10.3 10.3  9.7  9.4 10.5 11.
 10.  10.7]


In [26]:
df = pd.read_excel("statistic_id283093_number-of-homicides-in-england-and-wales-2002-2022.xlsx", "Data", header = 1)
df.head()
print(df)

z = dataframe_to_dictionary(df)
twelve_dates1 = z["Year"]

z = dataframe_to_dictionary(df)
homicide_rate1 = z["Number of homicides in England and Wales 2002-2022"]

twelve_dates = np.array(twelve_dates1)
print(twelve_dates)

homicide_rate = np.array(homicide_rate1)
print(homicide_rate)

    Year  Number of homicides in England and Wales 2002-2022
0   2012                                                553 
1   2013                                                558 
2   2014                                                533 
3   2015                                                539 
4   2016                                                575 
5   2017                                                711 
6   2018                                                716 
7   2019                                                683 
8   2020                                                714 
9   2021                                                570 
10  2022                                                710 
[2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022]
[553 558 533 539 575 711 716 683 714 570 710]


In [27]:
df = pd.read_excel("statistic_id283093_number-of-homicides-in-england-and-wales-2002-2022.xlsx", "Data2", header = 2)
df.head()
print(df)

z = dataframe_to_dictionary(df)
twelve_dates1 = z["Year"]

z = dataframe_to_dictionary(df)
gamingtwelve_rate1 = z["Games"]

twelve_dates = np.array(twelve_dates1)
print(twelve_dates)

gamingtwelve_rate = np.array(gamingtwelve_rate1)
print(gamingtwelve_rate)

    Year  Games
0   2012     35
1   2013     42
2   2014     44
3   2015     41
4   2016     37
5   2017     36
6   2018     38
7   2019     39
8   2020     62
9   2021     60
10  2022     58
[2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022]
[35 42 44 41 37 36 38 39 62 60 58]


In [28]:
df = pd.read_excel("statistic_id300521_uk-gaming-reach-2007-2021.xlsx", "Data", header = 2)
df.head()
print(df)

y = dataframe_to_dictionary(df)
video_gamer1 = y["Gamers"]

z = dataframe_to_dictionary(df)
data_dates1 = z["UK gaming reach 2007-2021"]

video_gamer = np.array(video_gamer1)
print(video_gamer)

data_dates = np.array(data_dates1)
print(data_dates)


    UK gaming reach 2007-2021  Gamers
0                        2007      31
1                        2008      33
2                        2009      36
3                        2010      34
4                        2011      37
5                        2012      35
6                        2013      42
7                        2014      44
8                        2015      41
9                        2016      37
10                       2017      36
11                       2018      38
12                       2019      39
13                       2020      62
14                       2021      60
15                       2022      58
[31 33 36 34 37 35 42 44 41 37 36 38 39 62 60 58]
[2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020
 2021 2022]


In [29]:
m, b = np.polyfit(data_dates, violent_crimes, 1)
Y = m * data_dates + b

fig = go.Figure()

# Original line plot
fig.add_trace(go.Scatter(
    x=data_dates,
    y=violent_crimes,
    mode='lines',
    name='Original Line',
    line=dict(color='rgba(255, 0, 0, 0.7)')
))

# Regression line
fig.add_trace(go.Scatter(
    x=data_dates,
    y=Y,
    mode='lines',
    name='Regression Line',
    line=dict(color='rgba(255, 255, 0, 0.9)', width=3)
))

fig.update_layout(
    xaxis_title="Years",
    yaxis_title="UK Violent Crime Offences",
    title="Adult Violent Crimes Offences in the UK from 2007-2022",
    width=800,  # Adjust the width as needed
    height=500
)

fig.show()

In [30]:
m, b = np.polyfit(data_dates, sexual_offences, 1)
Y = m * data_dates + b

fig = go.Figure()

# Original line plot
fig.add_trace(go.Scatter(
    x=data_dates,
    y=sexual_offences,
    mode='lines',
    name='Original Line',
    line=dict(color='rgba(255, 0, 0, 0.7)')
))

# Regression line
fig.add_trace(go.Scatter(
    x=data_dates,
    y=Y,
    mode='lines',
    name='Regression Line',
    line=dict(color='rgba(255, 255, 0, 0.9)', width=3)
))

fig.update_layout(
    xaxis_title="Years",
    yaxis_title="UK Sexual Offences",
    title="Adult Sexual Offences in the UK from 2007-2022",
    width=800,  # Adjust the width as needed
    height=500
)

fig.show()

In [31]:
m, b = np.polyfit(data_dates, weapon_possession, 1)
Y = m * data_dates + b

fig = go.Figure()

# Original line plot
fig.add_trace(go.Scatter(
    x=data_dates,
    y=weapon_possession,
    mode='lines',
    name='Original Line',
    line=dict(color='rgba(255, 0, 0, 0.7)')
))

# Regression line
fig.add_trace(go.Scatter(
    x=data_dates,
    y=Y,
    mode='lines',
    name='Regression Line',
    line=dict(color='rgba(255, 255, 0, 0.9)', width=3)
))

fig.update_layout(
    xaxis_title="Years",
    yaxis_title="UK Weapon Possession Offences",
    title="Adult Weappon Possession Offences in the UK from 2007-2022",
    width=800,  # Adjust the width as needed
    height=500
)

fig.show()

In [32]:
m, b = np.polyfit(twelve_dates, homicide_rate, 1)
Y = m * twelve_dates + b

fig = go.Figure()

# Original line plot
fig.add_trace(go.Scatter(
    x=twelve_dates,
    y=homicide_rate,
    mode='lines',
    name='Original Line',
    line=dict(color='rgba(255, 0, 0, 0.7)')
))

# Regression line
fig.add_trace(go.Scatter(
    x=twelve_dates,
    y=Y,
    mode='lines',
    name='Regression Line',
    line=dict(color='rgba(255, 255, 0, 0.9)', width=3)
))

fig.update_layout(
    xaxis_title="Years",
    yaxis_title="UK homicide Offences",
    title="Adult homicide rate in the UK from 2012-2022",
    width=800,  # Adjust the width as needed
    height=500
)

fig.show()

In [33]:
m, b = np.polyfit(data_dates, suicide_rate, 1)
Y = m * data_dates + b

fig = go.Figure()

# Original line plot
fig.add_trace(go.Scatter(
    x=data_dates,
    y=suicide_rate,
    mode='lines',
    name='Original Line',
    line=dict(color='rgba(255, 0, 0, 0.7)')
))

# Regression line
fig.add_trace(go.Scatter(
    x=data_dates,
    y=Y,
    mode='lines',
    name='Regression Line',
    line=dict(color='rgba(255, 255, 0, 0.9)', width=3)
))

fig.update_layout(
    xaxis_title="Years",
    yaxis_title="UK Suicide Rate",
    title="Adult Suicide Rate in the UK from 2007-2022",
    width=800,  # Adjust the width as needed
    height=500
)

fig.show()